version: '3'
services:
  python3:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: 'sp-python'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src